robot_ip: 192.168.1.10

# Hand-eye calibration result
hand_eye:
  parent: end_effector_link
  child: camera_link
  translation: [0.06041, -0.01027, 0.06052]              # x, y, z (m)
  rotation: [0.706184, -0.014006, 0.707857, 0.006797]  # qx, qy, qz, qw

base_frame: base_link
ee_link: end_effector_link
cloud_topic: /camera/camera/depth/color/points
settle_time: 5.0          
frames_per_view: 5        
speed: 0.1                
motion: cartesian         
cartesian_fallback: false 
view_voxel: 0.002         
max_depth: 0.40           

workspace:
  x: [0.30, 0.80]
  y: [-0.50, 0.50]
  z: [-0.30, 0.40]


views:
  - [0.329, -0.017, 0.390, 1.000, -0.017, -0.014, -0.012]    # view 0: [x, y, z, qx, qy, qz, qw]
  - [0.344, 0.183, 0.411, 0.990, -0.021, -0.034, 0.138]    # view 1:[x, y, z, qx, qy, qz, qw]

# Home: 
home: [0.329, -0.017, 0.391, 1.000, -0.017, -0.012, -0.011]  # [x, y, z, qx, qy, qz, qw]